language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t  ravis_env_var_exercise  .
  - docker tag  ravis_env_var_exercise  turbosaurio/ ravis_env_var_exercise :latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push turbosaurio/ ravis_env_var_exercise 
